channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - h5py
  - ipython
  - ipyparallel
  - jupyter
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - tensorflow
  - keras
  - pip
  - pip:
    - soundsig
    - neo
    - pynwb
