channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - h5py
  - ipython
  - ipyparallel
  - jupyter
  - matplotlib
  - pandas
  - numpy
  - scipy
  - scikit-image
  - scikit-learn
  - pynwb
  - pip
  - ruamel.yaml=0.15.37
  - pip:
    - soundsig
    - neo
